export const getVersion: () => string;
export const runGoSmoke: (rounds: number) => boolean;
export const runGoLifecycle: (cycles: number) => boolean;
export const startGoSmoke: () => boolean;
export const stopGoSmoke: () => boolean;
export const getGoSmokeTicks: () => number;
export const beginVpnProbe: () => boolean;
export const markVpnProtected: () => boolean;
export const attachVpnTun: (tunFd: number) => boolean;
export const failVpnProbe: (errorCode: number) => boolean;
export const stopVpnProbe: () => boolean;
export const getVpnProbeStatus: () => string;
export const getCurrentPid: () => number;
export const startEngine: (configJson: string, listener: (eventJson: string) => void) => Promise<boolean>;
export const stopEngine: () => Promise<boolean>;
export const networkChanged: () => void;
export const suspendVpnTun: () => boolean;
