export const getVersion: () => string;
export const runGoSmoke: (rounds: number) => boolean;
export const runGoLifecycle: (cycles: number) => boolean;
export const startGoSmoke: () => boolean;
export const stopGoSmoke: () => boolean;
export const getGoSmokeTicks: () => number;
export const beginVpnProbe: () => boolean;
export const markVpnProtected: () => boolean;
export const attachVpnTun: (tunFd: number) => boolean;
export const failVpnProbe: (errorCode: number) => boolean;
export const stopVpnProbe: () => boolean;
export const getVpnProbeStatus: () => string;
export const getCurrentPid: () => number;
export const getOpenFdCount: () => number;
export const initProbeChannel: (directory: string) => boolean;
export const writeProbeChannel: (key: number, value: string) => boolean;
export const startProbeChannelWatch: (mask: number, listener: (key: number, value: string) => void) => boolean;
export const stopProbeChannelWatch: () => void;
export const startEngine: (configJson: string, listener: (eventJson: string) => void) => Promise<boolean>;
export const stopEngine: () => Promise<boolean>;
export const logoutEngine: () => Promise<boolean>;
export const networkChanged: () => void;
export const suspendVpnTun: () => boolean;
export const probePeer: (target: string) => Promise<string>;
